/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const GalleryImage = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'blobId' : IDL.Text,
  'imageId' : IDL.Text,
  'uploadedAt' : IDL.Int,
});
export const Result = IDL.Record({
  'studentId' : IDL.Text,
  'studentName' : IDL.Text,
  'year' : IDL.Int,
  'score' : IDL.Text,
  'examName' : IDL.Text,
  'percentage' : IDL.Float64,
});
export const StudentInput = IDL.Record({
  'studentId' : IDL.Text,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'enrollmentDate' : IDL.Int,
  'phone' : IDL.Text,
  'course' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AdmissionEnquiry = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
  'course' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Student = IDL.Record({
  'studentId' : IDL.Text,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'enrollmentDate' : IDL.Int,
  'phone' : IDL.Text,
  'course' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addGalleryImage' : IDL.Func([GalleryImage], [], []),
  'addResult' : IDL.Func([Result], [], []),
  'addStudent' : IDL.Func([StudentInput], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deactivateStudent' : IDL.Func([IDL.Text], [], []),
  'deleteAdmissionEnquiry' : IDL.Func([IDL.Int], [], []),
  'getAllAdmissionEnquiries' : IDL.Func(
      [],
      [IDL.Vec(AdmissionEnquiry)],
      ['query'],
    ),
  'getAllGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
  'getAllResults' : IDL.Func([], [IDL.Vec(Result)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getResultsByExam' : IDL.Func([IDL.Text], [IDL.Vec(Result)], ['query']),
  'getResultsByStudent' : IDL.Func([IDL.Text], [IDL.Vec(Result)], ['query']),
  'getStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeGalleryImage' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitAdmissionEnquiry' : IDL.Func([AdmissionEnquiry], [], []),
  'updateStudent' : IDL.Func([IDL.Text, StudentInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const GalleryImage = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'blobId' : IDL.Text,
    'imageId' : IDL.Text,
    'uploadedAt' : IDL.Int,
  });
  const Result = IDL.Record({
    'studentId' : IDL.Text,
    'studentName' : IDL.Text,
    'year' : IDL.Int,
    'score' : IDL.Text,
    'examName' : IDL.Text,
    'percentage' : IDL.Float64,
  });
  const StudentInput = IDL.Record({
    'studentId' : IDL.Text,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'enrollmentDate' : IDL.Int,
    'phone' : IDL.Text,
    'course' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AdmissionEnquiry = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
    'course' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Student = IDL.Record({
    'studentId' : IDL.Text,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'enrollmentDate' : IDL.Int,
    'phone' : IDL.Text,
    'course' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addGalleryImage' : IDL.Func([GalleryImage], [], []),
    'addResult' : IDL.Func([Result], [], []),
    'addStudent' : IDL.Func([StudentInput], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deactivateStudent' : IDL.Func([IDL.Text], [], []),
    'deleteAdmissionEnquiry' : IDL.Func([IDL.Int], [], []),
    'getAllAdmissionEnquiries' : IDL.Func(
        [],
        [IDL.Vec(AdmissionEnquiry)],
        ['query'],
      ),
    'getAllGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
    'getAllResults' : IDL.Func([], [IDL.Vec(Result)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getResultsByExam' : IDL.Func([IDL.Text], [IDL.Vec(Result)], ['query']),
    'getResultsByStudent' : IDL.Func([IDL.Text], [IDL.Vec(Result)], ['query']),
    'getStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeGalleryImage' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitAdmissionEnquiry' : IDL.Func([AdmissionEnquiry], [], []),
    'updateStudent' : IDL.Func([IDL.Text, StudentInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };