/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdmissionEnquiry {
  'name' : string,
  'email' : string,
  'timestamp' : bigint,
  'phone' : string,
  'course' : string,
}
export interface GalleryImage {
  'title' : string,
  'description' : string,
  'blobId' : string,
  'imageId' : string,
  'uploadedAt' : bigint,
}
export interface Result {
  'studentId' : string,
  'studentName' : string,
  'year' : bigint,
  'score' : string,
  'examName' : string,
  'percentage' : number,
}
export interface Student {
  'studentId' : string,
  'name' : string,
  'isActive' : boolean,
  'email' : string,
  'enrollmentDate' : bigint,
  'phone' : string,
  'course' : string,
}
export interface StudentInput {
  'studentId' : string,
  'name' : string,
  'isActive' : boolean,
  'email' : string,
  'enrollmentDate' : bigint,
  'phone' : string,
  'course' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addGalleryImage' : ActorMethod<[GalleryImage], undefined>,
  'addResult' : ActorMethod<[Result], undefined>,
  'addStudent' : ActorMethod<[StudentInput], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deactivateStudent' : ActorMethod<[string], undefined>,
  'getAllAdmissionEnquiries' : ActorMethod<[], Array<AdmissionEnquiry>>,
  'getAllGalleryImages' : ActorMethod<[], Array<GalleryImage>>,
  'getAllResults' : ActorMethod<[], Array<Result>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getResultsByExam' : ActorMethod<[string], Array<Result>>,
  'getResultsByStudent' : ActorMethod<[string], Array<Result>>,
  'getStudents' : ActorMethod<[], Array<Student>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeGalleryImage' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitAdmissionEnquiry' : ActorMethod<[AdmissionEnquiry], undefined>,
  'updateStudent' : ActorMethod<[string, StudentInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];